name: Deploy to Azure

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push in Azure ACR
        run: |
          docker build . --file ./Dockerfile \
            --tag ${{ secrets.IMAGE_NAME }}:$GITHUB_RUN_NUMBER \
            $(env | grep '^BUILD_ARG_' | sed 's/^BUILD_ARG_/--build-arg /') \
            && docker tag ${{ secrets.IMAGE_NAME }}:$GITHUB_RUN_NUMBER ${{ secrets.IMAGE_NAME }}:latest \
            && docker push ${{ secrets.IMAGE_NAME }}:$GITHUB_RUN_NUMBER \
            && docker push ${{ secrets.IMAGE_NAME }}:latest

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      WEB_APP: app-name-azure

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Web App Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEB_APP }}
          images: ${{ secrets.IMAGE_NAME }}:latest
          slot-name: staging
